name: Docker Build and Push to Aliyun

on:
  push:
    branches:
      - main

env:
  ALIYUN_REGISTRY: crpi-lssazn1jp8ho54qv.cn-guangzhou.personal.cr.aliyuncs.com/docker-imges-c/docker-images
  ALIYUN_NAME_SPACE: docker-imges-c
  ALIYUN_REGISTRY_USER: aliyun2303696073
  ALIYUN_REGISTRY_PASSWORD: cwm147258

jobs:
  build-and-push:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Aliyun Container Registry
      run: |
        echo ${{ secrets.ALIYUN_REGISTRY_PASSWORD }} | docker login ${{ env.ALIYUN_REGISTRY }} -u ${{ env.ALIYUN_REGISTRY_USER }} --password-stdin

    - name: Pull Docker image
      run: docker pull ${{ env.ALIYUN_NAME_SPACE }}/gitlab/gitlab-ce:latest

    - name: Tag Docker image
      run: docker tag ${{ env.ALIYUN_NAME_SPACE }}/gitlab/gitlab-ce:latest ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/gitlab/gitlab-ce:latest

    - name: Push Docker image to Aliyun
      run: docker push ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAME_SPACE }}/gitlab/gitlab-ce:latest
