name: Docker

on:
  workflow_dispatch:
  push:
    branches: [main]




jobs:
  build-and-push:
    name: Build and Push Docker image to Aliyun
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Print all environment variables
      run: |
        echo "ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}"
        echo "ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}"
        echo "ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}"
        # 出于安全考虑，不建议打印密码或敏感信息
        # echo "ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Aliyun Container Registry
      run: |
        echo "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.ALIYUN_REGISTRY_USER }}" -p "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" "${{ secrets.ALIYUN_REGISTRY }}"

    - name: Pull and Push Docker image to Aliyun
      run: |
        docker pull gitlab/gitlab-ce:latest
        echo "Aliyun Registry: ${{ secrets.ALIYUN_REGISTRY }}"
        echo "Aliyun Name Space: ${{ secrets.ALIYUN_NAME_SPACE }}"
        docker tag gitlab/gitlab-ce:latest "${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/gitlab-ce:latest"
        docker push "$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/gitlab-ce:latest"
