name: Docker

on:
  workflow_dispatch:
  push:
    branches: [main]




jobs:
  build-and-push:
    name: Build and Push Docker image to Aliyun
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Aliyun Container Registry
      run: |
        echo cwm147258 | docker login -u aliyun2303696073 -p cwm147258 crpi-lssazn1jp8ho54qv.cn-guangzhou.personal.cr.aliyuncs.com

    - name: Pull and Push Docker image to Aliyun
      run: |
        docker pull gitlab/gitlab-ce:latest
        echo "Aliyun Registry: ${{ secrets.ALIYUN_REGISTRY }}"
        echo "Aliyun Name Space: ${{ secrets.ALIYUN_NAME_SPACE }}"
        docker tag "gitlab/gitlab-ce:latest crpi-lssazn1jp8ho54qv.cn-guangzhou.personal.cr.aliyuncs.com/docker-imges-c/gitlab-ce:latest"
        docker push "crpi-lssazn1jp8ho54qv.cn-guangzhou.personal.cr.aliyuncs.com/docker-imges-c/gitlab-ce:latest"
